pipeline {
    agent any

    environment {
        DOCKERHUB_CREDENTIALS = 'dockerhub-creds' // Replace with your Jenkins Docker Hub credentials ID
        DOCKERHUB_USERNAME = 'bharathi136'
    }

    stages {
        stage('Checkout') {
            steps {
                git credentialsId: 'github-creds', url: 'https://github.com/Bharathi1306/quickshop.git'
            }
        }

        stage('Build Services') {
            parallel {
                stage('Order Service') {
                    steps {
                        dir('frontend/quickshop-services/order-service') {
                            echo "⚙️ Building Order Service with Maven..."
                            sh 'mvn clean package -DskipTests'
                        }
                    }
                }
                stage('Product Service') {
                    steps {
                        dir('frontend/quickshop-services/product-service') {
                            echo "⚙️ Building Product Service with Maven..."
                            sh 'mvn clean package -DskipTests'
                        }
                    }
                }
                stage('User Service') {
                    steps {
                        dir('frontend/quickshop-services/user-service') {
                            echo "⚙️ Building User Service with Maven..."
                            sh 'mvn clean package -DskipTests'
                        }
                    }
                }
            }
        }

        stage('Build Docker Images') {
            steps {
                dir('frontend/quickshop-services') {
                    echo "🐳 Building Docker images..."
                    sh 'docker build -t ${DOCKERHUB_USERNAME}/order-service order-service/'
                    sh 'docker build
