pipeline {
    agent any
    stages {
        stage('Build Order Service') {
            steps {
                dir('frontend/quickshop-services/order-service') {
                    sh 'mvn clean package -DskipTests'
                }
            }
        }
        stage('Build Product Service') {
            steps {
                dir('frontend/quickshop-services/product-service') {
                    sh 'mvn clean package -DskipTests'
                }
            }
        }
        stage('Build User Service') {
            steps {
                dir('frontend/quickshop-services/user-service') {
                    sh 'mvn clean package -DskipTests'
                }
            }
        }
        stage('Build Docker Images') {
            steps {
                // Build Docker images for each service here
            }
        }
        stage('Push Docker Images') {
            steps {
                // Push Docker images to Docker Hub
            }
        }
    }
}
